version: '3.8'

services:
  id-vault:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: id-vault
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_WEB3AUTH_CLIENT_ID=${VITE_WEB3AUTH_CLIENT_ID}
      - VITE_WEB3AUTH_CLIENT_SECRET=${VITE_WEB3AUTH_CLIENT_SECRET}
      - VITE_WALLETCONNECT_PROJECT_ID=${VITE_WALLETCONNECT_PROJECT_ID}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        limits:
          cpus: '30.0'  # Allocate 30 of the 32 cores
          memory: 64G  # Allocate 120GB of the 128GB RAM
    runtime: nvidia     # Enable NVIDIA GPU support
    restart: unless-stopped