version: '3.8'

services:
  id-vault:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: id-vault
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./package.json:/app/package.json
      - node_modules_volume:/app/node_modules
    environment:
      - NODE_ENV=production
      - VITE_WEB3AUTH_CLIENT_ID=${VITE_WEB3AUTH_CLIENT_ID}
      - VITE_WEB3AUTH_CLIENT_SECRET=${VITE_WEB3AUTH_CLIENT_SECRET}
      - VITE_WALLETCONNECT_PROJECT_ID=${VITE_WALLETCONNECT_PROJECT_ID}
    restart: unless-stopped

volumes:
  node_modules_volume: